import type { Metadata } from "next";
import {
  Target,
  Link2,
  Eye,
  MessageSquareHeart,
  BarChart3,
  TrendingUp,
  Clock,
  ThumbsUp,
} from "lucide-react";
import { WaitlistForm } from "@/components/marketing/waitlist-form";
import {
  DoodleStar,
  MiniSparkle,
  DoodleHeart,
  SquigglyUnderline,
  Confetti,
  WobblyCircle,
  DoodleSmile,
} from "@/components/shared/illustrations";

export const metadata: Metadata = {
  title: "For Sales | Make & Send",
};

const FEATURES = [
  {
    icon: Link2,
    title: "CRM Integration",
    description:
      "Connect HubSpot, Salesforce, or Outreach. Trigger a bobblehead gift directly from your deal pipeline. No context switching, no extra tools.",
  },
  {
    icon: Eye,
    title: "Gift Tracking Pages",
    description:
      "Every gift gets a personalized landing page. Know the moment your prospect opens the package, views the reveal, and shares it with their team.",
  },
  {
    icon: MessageSquareHeart,
    title: "Personalized Messages",
    description:
      "Include a custom message referencing their company, recent funding round, or a deal milestone. Make it personal. Make it impossible to ignore.",
  },
  {
    icon: BarChart3,
    title: "ROI Analytics",
    description:
      "Track meetings booked, deals influenced, and pipeline generated by gifting campaigns. Show your VP of Sales the numbers that justify every dollar.",
  },
];

const STATS = [
  {
    icon: ThumbsUp,
    value: "97%",
    label: "of recipients keep it on their desk for 12+ months",
  },
  {
    icon: TrendingUp,
    value: "3.2x",
    label: "higher response rate vs. cold email alone",
  },
  {
    icon: Clock,
    value: "68%",
    label: "of prospects book a meeting within 14 days",
  },
];

export default function ForSalesPage() {
  return (
    <>
      {/* ── HERO ── Dark navy ── */}
      <section className="relative bg-gradient-to-br from-navy via-[#1f1a2e] to-navy overflow-hidden">
        <div className="absolute top-20 left-10 size-72 rounded-full bg-coral/10 blur-3xl" />
        <div className="absolute bottom-10 right-10 size-96 rounded-full bg-gold/10 blur-3xl" />
        <DoodleStar className="absolute top-16 right-[12%] size-8 text-gold/20 animate-pulse" />
        <MiniSparkle className="absolute bottom-20 left-[15%] size-5 text-gold/15 animate-pulse [animation-delay:1s]" />

        <div className="relative mx-auto max-w-7xl px-5 sm:px-8 lg:px-10 py-24 sm:py-32">
          <div className="mx-auto max-w-3xl text-center">
            <p className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-1.5 text-sm font-medium text-gold backdrop-blur-sm">
              <Target className="size-4" />
              Your unfair advantage in outreach
            </p>
            <h1 className="mt-8 text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-cream leading-[1.1]">
              Cold outreach they&apos;ll never{" "}
              <span className="relative inline-block">
                <span className="font-accent text-gold italic">forget</span>
                <SquigglyUnderline className="absolute -bottom-2 left-0 w-full h-3 text-gold/40" />
              </span>
            </h1>
            <p className="mt-6 text-lg sm:text-xl text-cream/70 leading-relaxed max-w-2xl mx-auto">
              Forget cold emails that get deleted. Send a hand-sculpted
              bobblehead of your prospect. It lands on their desk, stays there
              for years, and gets you the meeting. This is cold gifting.
            </p>
          </div>
        </div>
      </section>

      {/* ── IMAGINE THIS ── Cream background ── */}
      <section className="relative bg-cream py-24 sm:py-32 overflow-hidden">
        <DoodleHeart className="absolute top-16 right-[8%] size-8 text-coral/15" />
        <DoodleSmile className="absolute bottom-20 left-[5%] size-10 text-navy/[0.06]" />

        <div className="relative mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">
          <div className="mx-auto max-w-3xl">
            <p className="text-sm font-semibold uppercase tracking-wider text-coral">
              Picture this
            </p>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold text-navy">
              Imagine{" "}
              <span className="relative inline-block">
                <span className="font-accent text-coral italic">this</span>
                <SquigglyUnderline className="absolute -bottom-1 left-0 w-full h-2.5 text-coral/30" />
              </span>
            </h2>

            <div className="relative mt-10 rounded-3xl bg-white p-8 sm:p-10 shadow-sm">
              <Confetti className="absolute -top-4 -right-4 w-24 h-24 opacity-40" />
              <div className="relative space-y-6 text-base text-navy/70 leading-relaxed">
                <p>
                  Your top prospect — the one who&apos;s ignored four emails and
                  two LinkedIn messages — just received a package. Inside is a
                  hand-sculpted bobblehead that looks exactly like them — full body,
                  wearing their company hoodie with your logo on the sleeve. The base
                  reads{" "}
                  <span className="font-semibold text-navy">
                    &ldquo;{"{name}"} — The Deal Closer of {new Date().getFullYear()}&rdquo;
                  </span>
                  .
                </p>
                <p>
                  They laugh out loud. They put it on their desk. A colleague
                  walks by: &ldquo;Where did you get that?&rdquo; They post it
                  on LinkedIn. Your brand is now a conversation happening without
                  you in the room.
                </p>
                <p>
                  Two days later, they reply to your email:{" "}
                  <span className="font-semibold text-navy">
                    &ldquo;Okay, I have to meet the team behind this.
                    Let&apos;s talk.&rdquo;
                  </span>
                </p>
                <p>
                  That is cold gifting. Not a gift card that gets forgotten in an
                  inbox. Not swag that ends up in a drawer. A permanent,
                  personal, desk-sized billboard for your brand that makes them
                  smile every single day.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── FEATURES ── White background ── */}
      <section className="relative bg-white py-24 sm:py-32 overflow-hidden">
        <Confetti className="absolute bottom-0 right-0 w-32 h-32 opacity-30 rotate-90" />

        <div className="relative mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">
          <div className="text-center">
            <p className="text-sm font-semibold uppercase tracking-wider text-coral">
              Your sales toolkit
            </p>
            <h2 className="mt-3 text-3xl sm:text-4xl lg:text-5xl font-bold text-navy">
              Everything you need to{" "}
              <span className="relative inline-block">
                <span className="font-accent text-coral italic">close</span>
                <SquigglyUnderline className="absolute -bottom-1 left-0 w-full h-2.5 text-coral/30" />
              </span>
            </h2>
          </div>

          <div className="mt-16 grid gap-8 sm:grid-cols-2">
            {FEATURES.map((feature) => (
              <div
                key={feature.title}
                className="group relative rounded-3xl bg-cream p-8 shadow-sm transition-all hover:shadow-lg hover:-translate-y-1"
              >
                <div className="relative mb-6">
                  <WobblyCircle className="absolute -top-2 -left-2 size-20 text-coral/[0.07] transition-all group-hover:text-coral/15" />
                  <div className="relative inline-flex size-14 items-center justify-center rounded-2xl bg-navy text-cream">
                    <feature.icon className="size-6" />
                  </div>
                </div>
                <h3 className="text-lg font-bold text-navy">{feature.title}</h3>
                <p className="mt-2 text-sm text-navy/60 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── STATS ── Navy background ── */}
      <section className="relative bg-navy py-24 sm:py-32 overflow-hidden">
        <DoodleStar className="absolute top-12 left-[8%] size-10 text-gold/15 animate-pulse" />
        <MiniSparkle className="absolute bottom-20 right-[10%] size-6 text-coral/15 animate-pulse [animation-delay:1s]" />

        <div className="relative mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">
          <div className="text-center">
            <p className="text-sm font-semibold uppercase tracking-wider text-gold">
              The numbers speak
            </p>
            <h2 className="mt-3 text-3xl sm:text-4xl lg:text-5xl font-bold text-cream">
              Numbers that{" "}
              <span className="relative inline-block">
                <span className="font-accent text-gold italic">close</span>
                <SquigglyUnderline className="absolute -bottom-1 left-0 w-full h-2.5 text-gold/40" />
              </span>
            </h2>
          </div>

          <div className="mt-16 grid gap-8 sm:grid-cols-3">
            {STATS.map((stat) => (
              <div
                key={stat.label}
                className="relative rounded-3xl bg-white/5 border border-white/10 p-8 text-center backdrop-blur-sm transition-all hover:-translate-y-1"
              >
                <div className="mx-auto mb-4 inline-flex size-14 items-center justify-center rounded-2xl bg-gold/20 text-gold">
                  <stat.icon className="size-6" />
                </div>
                <p className="text-5xl font-bold text-gold">{stat.value}</p>
                <p className="mt-3 text-sm text-cream/60 leading-relaxed">
                  {stat.label}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── WAITLIST CTA ── Cream background ── */}
      <section className="relative bg-cream py-24 sm:py-32 overflow-hidden">
        <DoodleSmile className="absolute top-16 right-[10%] size-10 text-navy/[0.06]" />
        <DoodleHeart className="absolute bottom-20 left-[8%] size-8 text-coral/10" />

        <div className="relative mx-auto max-w-3xl px-5 sm:px-8 lg:px-10 text-center">
          <Confetti className="mx-auto w-20 h-20 mb-4 opacity-60" />
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-navy leading-tight">
            Ready to make outreach{" "}
            <span className="relative inline-block">
              <span className="font-accent text-coral italic">unforgettable</span>
              <SquigglyUnderline className="absolute -bottom-1 left-0 w-full h-2.5 text-coral/30" />
            </span>
            ?
          </h2>
          <p className="mt-4 text-lg text-navy/60">
            Be first to deploy bobblehead-powered outreach. The teams that
            move first win the most meetings.
          </p>
          <WaitlistForm variant="light" />
        </div>
      </section>
    </>
  );
}
